// components/Icon.tsx
import { LucideProps } from 'lucide-react';
import {
    Activity,
    AlertCircle,
    AlertTriangle,
    BadgeX,
    Ban,
    BookKey,
    Bookmark,
    BookOpen,
    BringToFront,
    Building,
    Calendar,
    CalendarFold,
    Check,
    CheckCircle,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    CircuitBoard,
    Clock,
    Copy,
    Cpu,
    Crosshair,
    Download,
    Drama,
    ExternalLink,
    Eye,
    EyeOff,
    Feather,
    File,
    FileAudio,
    FileSliders,
    FileText,
    Flame,
    FlaskConical,
    FlipVertical,
    Folder,
    GalleryHorizontal,
    Github,
    Hammer,
    HandCoins,
    Heart,
    HelpCircle,
    History,
    Home,
    Image,
    Info,
    Key,
    Layers,
    Link2,
    ListTree,
    Loader2,
    Lock,
    LogIn,
    LogOut,
    Mail,
    Map,
    MapPin,
    MapPinHouse,
    MapPinned,
    Menu,
    MessageCircle,
    MessageSquare,
    MessageSquareDot,
    Mic,
    Milestone,
    Pause,
    Phone,
    Pilcrow,
    Play,
    Puzzle,
    Radar,
    SatelliteDish,
    ScanLine,
    ScrollText,
    SearchCode,
    Send,
    Share2,
    Shapes,
    Shield,
    ShieldCheck,
    Sparkles,
    Sprout,
    SquareActivity,
    SquareChevronRight,
    SquareCode,
    SquareLibrary,
    Squirrel,
    Tally1,
    Tally2,
    Tally3,
    Tally4,
    Tally5,
    TreeDeciduous,
    Trees,
    TrendingUp,
    Unlock,
    User,
    UserPlus,
    Users,
    UserX,
    Video,
    Volume2,
    VolumeX,
    WavesLadder,
    Workflow,
    X,
    XCircle,
    Zap,
} from 'lucide-react';

const iconMap = {
    Activity,
    AlertCircle,
    AlertTriangle,
    BadgeX,
    Ban,
    BookKey,
    Bookmark,
    BookOpen,
    BringToFront,
    Building,
    Calendar,
    CalendarFold,
    Check,
    CheckCircle,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    CircuitBoard,
    Clock,
    Copy,
    Cpu,
    Crosshair,
    Download,
    Drama,
    ExternalLink,
    Eye,
    EyeOff,
    Feather,
    File,
    FileAudio,
    FileSliders,
    FileText,
    Flame,
    FlaskConical,
    FlipVertical,
    Folder,
    GalleryHorizontal,
    Github,
    Hammer,
    HandCoins,
    Heart,
    HelpCircle,
    History,
    Home,
    Image,
    Info,
    Key,
    Layers,
    Link2,
    ListTree,
    Loader2,
    Lock,
    LogIn,
    LogOut,
    Mail,
    Map,
    MapPin,
    MapPinHouse,
    MapPinned,
    Menu,
    MessageCircle,
    MessageSquare,
    MessageSquareDot,
    Mic,
    Milestone,
    Pause,
    Phone,
    Pilcrow,
    Play,
    Puzzle,
    Radar,
    SatelliteDish,
    ScanLine,
    ScrollText,
    SearchCode,
    Send,
    Share2,
    Shapes,
    Shield,
    ShieldCheck,
    Sparkles,
    Sprout,
    SquareActivity,
    SquareChevronRight,
    SquareCode,
    SquareLibrary,
    Squirrel,
    Tally1,
    Tally2,
    Tally3,
    Tally4,
    Tally5,
    TreeDeciduous,
    Trees,
    TrendingUp,
    Unlock,
    User,
    UserPlus,
    Users,
    UserX,
    Video,
    Volume2,
    VolumeX,
    WavesLadder,
    Workflow,
    X,
    XCircle,
    Zap,
} as const;

export type IconName = keyof typeof iconMap;

type IconProps = Omit<LucideProps, 'ref'> & {
    name: IconName;
    className?: string;
};

export default function Icon({
                                 name,
                                 className = '',
                                 size = 20,
                                 strokeWidth = 2,
                                 ...props
                             }: IconProps) {
    const IconComponent = iconMap[name];

    if (!IconComponent) {
        console.warn(`Icon "${name}" not found in whitelist.`);
        return <HelpCircle className={className} size={size} strokeWidth={strokeWidth} {...props} />;
    }

    return <IconComponent className={className} size={size} strokeWidth={strokeWidth} {...props} />;
}